### ISSUE TITLE
A query for you

### ISSUE THREAD

**Issue by ravibpatel91** [adamsanderson/jQuery-File-Validator#1]
Hello, Adam
Can we check multiple file types using this validator plugin ?
Like file can be Image OR PDF ?
Please suggest me the code to use.
because, in documentation it was not included.

**Comment by adamsanderson** [comment]
Hi @ravi22691, you can match against content types such as "image/png" using a regular expression.  So try this out, configure it with: `onValidation: /image|pdf/`.  I think that should work just fine.
