### ISSUE TITLE
Hi,I think the jQuery-File-Validator/js/file-validator.js may be wrong

### ISSUE THREAD

**Issue by zhubj** [adamsanderson/jQuery-File-Validator#3]
type: function(contentType, invalid){
      var isValid;
      if( typeof contentType == 'function' ){ 
        isValid = contentType; 
      } else if (contentType.constructor === RegExp ) { 
        isValid = function(type){ return type.match(contentType); }; 
      } else { 
        isValid = function(type){ return ~type.indexOf(contentType); }; 
      }

I think it should be like this:
type -> file.type
contentType -> your RegExp str

I want validate a file is a cvs or not:
so: jQuery('[type=file]').fileValidator({
    maxSize:      '100k', //optional
    type:         '(text/csv|application/vnd.ms-excel|text/plain|text/tsv|application/vnd.msexcel)$' //optional

```
}
);
```

so,this is I think:

type: function(contentType, invalid){
      var isValid;
      if( typeof contentType == 'function' ){ 
        isValid = contentType; 
      } else if (contentType.constructor === RegExp ) { 
        isValid = function(type){  return contentType.match(type); }; 
      } else { 
        isValid = function(type){ return ~contentType.indexOf(type); }; 
      }

**Comment by adamsanderson** [comment]
Hi @zhubj, 
You're passing in a regular expression as a string in the example above.  I think what you want is:

```
type: /(text\/csv)|(application\/vnd.ms-excel)|(text\/plain)|(text\/tsv)|(application\/vnd.msexcel)' //optional
```

It's awkward, but you need to escape the `/`s inside the expression, hence: `\/`, and then to use alternating groups it's probably simplest to wrap the content types in parens.

**Comment by zhubj** [comment]
@adamsanderson Thank you, I got it. i found my error, I changed my code by your post,  and it work perfectly now.You made my day!
